kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1beta1
metadata:
  name: quayecosystems.quay.coreos.com
spec:
  subresources:
    status: {}
  names:
    plural: quayecosystems
    singular: quayecosystem
    shortNames:
      - quay
      - quays
    kind: QuayEcosystem
    listKind: QuayEcosystemList
    categories:
      - olm
  scope: Namespaced
  conversion:
    strategy: None
  preserveUnknownFields: false
  version: v1alpha1
  validation:
    openAPIV3Schema:
      description: QuayEcosystem represents a full Quay installation.
      type: object
      required:
        - metadata
        - spec
      properties:
        apiVersion:
          description: >-
            APIVersion defines the versioned schema of this representation of an
            object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info:
            https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
          type: string
        kind:
          description: >-
            Kind is a string value representing the REST resource this object
            represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info:
            https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
          type: string
        metadata:
          type: object
        spec:
          type: object
          required:
            - configBundleSecret
          properties:
            desiredVersion:
              description: The version of Quay and its components to deploy. Changing this value triggers an update.
              type: string
            configBundleSecret:
              description: Reference to a Secret containing Quay's config and extra SSL certs.
              type: string
            managedComponents:
              description: Components that will be managed by the Operator.
              type: array
              items:
                type: object
                required:
                  - kind
                properties:
                  kind: 
                    description: The kind of component.
                    type: string
        status:
          type: object
          properties:
            registryEndpoint:
              description: The external IP address of the Quay registry.
              type: string
            conditions:
              description: Conditions of the Quay ecosystem.
              type: array
              items:
                type: object
                properties:
                  type:
                    type: string
                  reason:
                    type: string
                  message:
                    type: string
                  lastHeartbeatTime:
                    type: string
                  lastTransitionTime:
                    type: string
  versions:
    - name: v1alpha1
      served: true
      storage: true
  group: quay.coreos.com
